/**
 * serve-nike-reviews.ts
 *
 * Reads data/nike-reviews.json and serves a clean HTML review page at
 * http://localhost:4444
 *
 * Run:  npx ts-node scripts/serve-nike-reviews.ts
 */

import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';

const PORT = 4444;
const DATA_FILE = path.join(__dirname, '..', 'data', 'nike-reviews.json');

function starBar(ratingText: string): string {
  // ratingText looks like "4.0 out of 5 stars" or "4,0 von 5 Sternen"
  const match = ratingText.match(/(\d+([.,]\d)?)/);
  const value = match ? parseFloat(match[1].replace(',', '.')) : 0;
  const full = Math.round(value);
  return '★'.repeat(full) + '☆'.repeat(5 - full);
}

function buildHtml(data: any): string {
  const reviews: any[] = data.reviews ?? [];
  const bugs: string[] = data.bugs ?? [];

  const reviewCards = reviews
    .map(
      (r) => `
    <div class="card">
      <div class="card-header">
        <span class="stars">${starBar(r.rating)}</span>
        <span class="rating-text">${escHtml(r.rating)}</span>
        ${r.verifiedPurchase ? '<span class="badge">Verified Purchase</span>' : ''}
      </div>
      <h3 class="review-title">${escHtml(r.title)}</h3>
      <p class="meta">${escHtml(r.author)} &mdash; ${escHtml(r.date)}</p>
      <p class="body">${escHtml(r.body)}</p>
    </div>`
    )
    .join('\n');

  const bugSection =
    bugs.length > 0
      ? `<section class="bugs">
          <h2>&#9888; Bugs / Issues Noted During Scrape</h2>
          <ul>${bugs.map((b) => `<li>${escHtml(b)}</li>`).join('')}</ul>
        </section>`
      : '<section class="bugs ok"><p>&#10003; No bugs encountered during scrape.</p></section>';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Nike Shoes Reviews</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: #f5f5f5; color: #222; }
    header { background: #232f3e; color: #fff; padding: 1.5rem 2rem; }
    header h1 { font-size: 1.5rem; }
    header p  { font-size: 0.9rem; opacity: .75; margin-top: .25rem; }
    .meta-bar { display: flex; gap: 2rem; background: #fff; padding: 1rem 2rem;
                border-bottom: 1px solid #ddd; flex-wrap: wrap; }
    .meta-bar span { font-size: 0.95rem; }
    .meta-bar .big { font-size: 1.4rem; font-weight: 700; color: #c45500; }
    main { max-width: 860px; margin: 2rem auto; padding: 0 1rem; }
    .card { background: #fff; border: 1px solid #ddd; border-radius: 8px;
            padding: 1.25rem 1.5rem; margin-bottom: 1rem;
            box-shadow: 0 1px 3px rgba(0,0,0,.07); }
    .card-header { display: flex; align-items: center; gap: .5rem; margin-bottom: .5rem; }
    .stars { color: #f90; font-size: 1.1rem; letter-spacing: 2px; }
    .rating-text { font-size: .85rem; color: #555; }
    .badge { background: #e7f3fe; color: #0a6; border-radius: 4px;
             font-size: .75rem; padding: 2px 6px; font-weight: 600; }
    .review-title { font-size: 1rem; font-weight: 600; margin-bottom: .25rem; }
    .meta { font-size: .8rem; color: #888; margin-bottom: .5rem; }
    .body { font-size: .92rem; line-height: 1.6; color: #333; }
    .bugs { max-width: 860px; margin: 0 auto 2rem; padding: 0 1rem; }
    .bugs h2 { color: #c00; margin-bottom: .5rem; }
    .bugs ul { padding-left: 1.25rem; }
    .bugs li { margin-bottom: .4rem; font-size: .9rem; }
    .bugs.ok p { color: #0a6; font-weight: 600; }
    footer { text-align: center; padding: 2rem; font-size: .8rem; color: #999; }
    a { color: #0066c0; }
  </style>
</head>
<body>
  <header>
    <h1>Nike Shoes &mdash; Amazon Reviews</h1>
    <p>Product: <a href="${escAttr(data.productUrl)}" target="_blank" rel="noopener">${escHtml(data.productTitle)}</a></p>
  </header>
  <div class="meta-bar">
    <span>Scraped: <strong>${escHtml(data.scrapedAt)}</strong></span>
    <span>Avg rating: <span class="big">${escHtml(data.averageRating)}</span></span>
    <span>Total ratings: <strong>${escHtml(data.totalRatings)}</strong></span>
    <span>Reviews shown: <strong>${reviews.length}</strong></span>
  </div>
  <main>
    ${reviewCards || '<p>No reviews extracted.</p>'}
  </main>
  ${bugSection}
  <footer>Generated by amazon-nike-reviews.ts &bull; Powered by Playwright</footer>
</body>
</html>`;
}

function escHtml(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escAttr(s: unknown): string {
  return String(s ?? '').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

const server = http.createServer((_req, res) => {
  if (!fs.existsSync(DATA_FILE)) {
    res.writeHead(503, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end(
      'data/nike-reviews.json not found.\n' +
        'Run the scraper first:\n  npx ts-node scripts/amazon-nike-reviews.ts\n'
    );
    return;
  }

  let data: any;
  try {
    data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf-8'));
  } catch (e) {
    res.writeHead(500, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end(`Failed to parse ${DATA_FILE}: ${e}`);
    return;
  }

  const html = buildHtml(data);
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
  res.end(html);
  console.log(`  GET / — served ${reviews_count(data)} reviews`);
});

function reviews_count(data: any): number {
  return Array.isArray(data?.reviews) ? data.reviews.length : 0;
}

server.listen(PORT, () => {
  console.log(`\n  Nike Reviews server running at http://localhost:${PORT}`);
  console.log('  Press Ctrl+C to stop.\n');
});
